### ISSUE TITLE
gpt审计代码报错

### ISSUE THREAD

**Issue by nasdadadada** [yuag/Code-audit#5]
Traceback (most recent call last):
  File "D:\1\php\Code-audit-main\Code_audit.py", line 227, in code_audit
    self.audit_directory(code_path, api_key)
  File "D:\1\php\Code-audit-main\Code_audit.py", line 258, in audit_directory
    self.audit_single_file(file_path, api_key)
  File "D:\1\php\Code-audit-main\Code_audit.py", line 249, in audit_single_file
    except openai.error.RateLimitError:
AttributeError: module 'openai' has no attribute 'error'

**Comment by yuag** [comment]
https://github.com/yuag/Code-audit/releases/tag/1.2

已修复
